name: Reusable workflow example in folder

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pass input and secrets to my-action
        uses: ./.github/workflows/my-action
        with:
          username: ${{ inputs.username }}
