# This is a basic workflow to help you get started with Actions

name: test api

on:
#   this workflow will run after 'test input' is 'completed'
#    workflow_run:
#      workflows: [test input]
#      types: [completed]
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: dispatches
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
      - name: call enhancement
        run: |
          curl -X POST https://api.github.com/repos/ccyandy9582/hello-action/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -d '{"event_type": "ping", "client_payload": {"repository": "'"$GITHUB_REPOSITORY"'"}}'