# This is a basic workflow to help you get started with Actions

name: enhancement of xxxx

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
  repository_dispatch:
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './hello-action'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: checkout another repo
        uses: actions/checkout@master
        with:
          repository: ccyandy9582/js-data-structure-and-algorithms
          token: ${{secrets.GITHUB_TOKEN}}
          path: './Todo'
      - name: show directory with 2 repos
        run: ls -al
      - name: list Todo
        run: ls -al ./Todo
      - name: list hello-action
        run: ls -al ./hello-action

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: run test
        run: |
          cd ./Todo
          npm run test
  callFromAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Event Enformation
        if: github.event.action == 'ping'
        run: |
          echo "Event '${{github.event.action}}' received from '${{github.event.client_payload.repository}}'"
