name: Call a reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  show-pwd:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -al ./.github/workflows/
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/reuse

  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/reuseWithParam
        with:
          username: mona1234
