name: Call a reusable workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: ./.github/workflows/reuse.yaml
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  call-workflow-passing-data:
    uses: ./.github/workflows/reuseWithParam.yaml
    with:
      username: "asdjhasjdhui1"
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
