name: Call a reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: ./.github/workflows/resue.yaml

  call-workflow-passing-data:
    uses: ./.github/workflows/reuseWithParams.yaml
    with:
      username: "asdjhasjdhui1"
