name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  show-pwd:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -al
  call-workflow:
    runs-on: ubuntu-latest
    steps: 
      - uses: ./.github/workflows/reuse.yaml

  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps: 
      - uses: ./.github/workflows/reuseWithParam.yaml
        with:
          username: mona1234
