name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: show path
        run: echo pwd
      - uses: ./.github/workflows/reuse.yaml

  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: ./.github/workflows/reuseWithParam.yaml
        with:
          username: mona1234