name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  show-pwd:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          pwd
  call-workflow:
    uses: ./.github/workflows/reuse.yaml

  call-workflow-passing-data:
    uses: ./.github/workflows/reuseWithParam.yaml
    with:
      username: mona1234
