name: Call a reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  show-pwd:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -al ./.github/workflows/

  call-workflow-passing-data:
    uses: ccyandy9582/hello-action/.github/workflows/reuseWithParam.yaml@main
    with:
      username: "asdjhasjdhui1"
          
