name: Call a reusable workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: ./.github/workflows/resue.yaml
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  call-workflow-passing-data:
    uses: ./.github/workflows/reuseWithParam.yaml
    with:
      username: "asdjhasjdhui1"
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
