# This is a basic workflow to help you get started with Actions

name: checkout svn

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: ./git
      - name: install svn
        run: |
          sudo apt-get install subversion
          sudo apt-get install apache2
          sudo apt-get install apache2-utils
      - name: check svn version
        run: svn --version
      - name: create new repo
        run: |
          sudo mkdir -p /svn/repos/springcloud
          sudo svnadmin create /svn/repos/springcloud
          sudo chmod 777 /svn/repos/springcloud
          sudo chown -R www-data:www-data /svn/repos/
          ls -al /svn/repos/springcloud/conf
          sudo sed -i 's!\# harry_sally_and_joe = harry,sally,&joe!\# harry_sally_and_joe = harry,sally,&joe\n\[/\]\n=rw!1' /svn/repos/springcloud/conf/authz
          
          sudo sed -i 's!sallyssecret!sallyssecret\nadmin=123!g' /svn/repos/springcloud/conf/passwd
          
          sudo sed -i 's!# anon-access = read!anon-access = read\nauth-access = write!g' /svn/repos/springcloud/conf/svnserve.conf
          sudo sed -i 's!# password-db = passwd!password-db = passwd!g' /svn/repos/springcloud/conf/svnserve.conf
          sudo sed -i 's!# authz-db = authz!authz-db = authz!g' /svn/repos/springcloud/conf/svnserve.conf
          
          sudo chown -R daemon /svn/repos
          sudo chmod -R 755 /svn/repos
      - name: start svn
        run: |
          sudo svnserve -d -r /svn/repos/
          netstat -ntlp |grep 3690
      - name: "ipconfig"
        run: ifconfig
      - name: checkout
        run: |
          mkdir ./checkout
          ls -al
          cd ./checkout
          svn co svn://localhost/springcloud --username admin --password 123
          ls -al
          cd ..
          ls -al
      - name: move git to svn
        run: |
          mv ./git/ ./checkout/springcloud
          ls -al ./checkout/springcloud
      - name: commit
        run: |
          cd ./checkout/springcloud
          ls -al
          svn add ./git
          sudo svn ci -m "hi, svn" --username admin --password 123
          svn info
      - name: varify commit result
        run: |
          cd ..
          cd ..
          mkdir new_co
          cd new_co
          svn co svn://localhost/springcloud --username admin --password 123
          cd springcloud
          ls -al