name: after secret POC

on:
  workflow_run: [secret POC]

jobs:
  secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./repo
      - name: "say hello"
        run: echo "hello"
