name: after secret POC

on:
   workflow_run:
     workflows: [secret POC]
     types: [completed]

jobs:
  secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./repo
      - name: "say hello"
        run: echo "hello"
