# This is a basic workflow to help you get started with Actions

name: test no yaml repo

on:
  workflow_dispatch:

jobs:
  no-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: run no yaml script
      - uses: actions/checkout@v2
        with:
          repository: ccyandy9582/no-yaml-actions
          token: ${{secrets.GITHUB_TOKEN}}
          path: './noYaml'
        run: |
          ls .
          cd ./noYaml
          ls .
          sh hello.sh