# This is a basic workflow to help you get started with Actions

name: test no yaml repo

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: run no yaml script
        uses: action/checkout@v2
          with:
            path: './noYaml'
        run: |
          ls .
          cd ./noYaml
          ls .
          sh hello.sh