# This is a basic workflow to help you get started with Actions

name: push file

on:
  workflow_dispatch:

jobs:
  no-yaml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: create new file
        run: |
          touch foo.txt
          ls
      - name: commit
        uses: EndBug/add-and-commit@v8
        with:
          push: true
