name: secret POC

on:
  workflow_dispatch:

env:
  env_secret: ${{secrets.ENV_SECRET}}
  repo_secret: ${{secrets.TEST_SECRET}}

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "show env_secret"
        run: echo $env_secret
      - name: "show repo_secret"
        run: echo $repo_secret
      - name: install svn
        run: sudo apt-get install subversion
      - name: check svn version
        run: svn --version
      - name: create new svn project
        run: |
          mkdir myproject
          svnadmin create /myproject
          ls
          ls ./myproject
