name: secret POC

on:
  workflow_dispatch:

env:
  env_secret: ${{secrets.ENV_SECRET}}
  repo_secret: ${{secrets.TEST_SECRET}}

jobs:
  secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./repo
      - name: "show env_secret"
        run: echo ${{secrets.ENV_SECRET}}
      - name: "show repo_secret"
        run: echo $repo_secret
      - name: install svn
        run: |
          sudo apt-get install subversion
          sudo apt-get install apache2
          sudo apt-get install apache2-utils
      - name: check svn version
        run: svn --version
      - name: create new repo
        run: |
          sudo mkdir -p /svn/repos/springcloud_config
          sudo svnadmin create /svn/repos/springcloud_config
          sudo chmod 777 /svn/repos/springcloud_config
          sudo chown -R www-data:www-data /svn/repos/
      - name: start svn
        run: |
          svnserve -d -r /svn/repos/
          netstat -ntlp |grep 3690
      - name: "ipconfig"
        run: ifconfig
      - name: commit to svn
        run: |
          svn import ./repo svn://10.1.0.166/springcloud_config 
          echo 1