name: secret POC

on:
  workflow_dispatch:

env:
  env_secret: ${{secret.ENV_SECRET}}
  repo_secret: ${{secret.TEST_SECRET}}

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "show env_secret"
        run: echo $env_secret
      - name: "show repo_secret"
        run: echo $repo_secret