name: secret POC

on:
  workflow_dispatch:

env:
  env_secret: ${{secrets.ENV_SECRET}}
  repo_secret: ${{secrets.TEST_SECRET}}

jobs:
  secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./repo
      - name: "show env_secret"
        run: echo ${{secrets.ENV_SECRET}}
      - name: "show repo_secret"
        run: echo $repo_secret
      - name: install svn
        run: |
          sudo apt-get install subversion
          sudo apt-get install apache2
          sudo apt-get install apache2-utils
      - name: check svn version
        run: svn --version
      - name: create new repo
        run: |
          sudo mkdir -p /home/svn/springcloud_config
          sudo svnadmin create /home/svn/springcloud_config
          sudo chmod 777 /home/svn/springcloud_config
          sudo chown -R www-data:www-data /home/svn/
      - name: start svn
        run: |
          svnserve -d -r /home/svn/
          netstat -ntlp |grep 3690
      - name: copy github repo to svn workspace
        run: |
          mv ./repo/* /home/svn/springcloud_config/
          ls /home/svn/springcloud_config
      - name: commit to svn
        run: |
          svn checkout /home/svn/springcloud_config
          echo 1
          svn add ./repo
          echo 2
          svn commit