name: secret POC

on:
  workflow_dispatch:

env:
  env_secret: ${{secrets.ENV_SECRET}}
  repo_secret: ${{secrets.TEST_SECRET}}

jobs:
  secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./repo
      - name: "show env_secret"
        run: echo ${{secrets.ENV_SECRET}}
      - name: "show repo_secret"
        run: echo $repo_secret